/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as LibraryRouteImport } from "./routes/library";
import { Route as LogsRouteImport } from "./routes/logs";
import { Route as OverviewRouteImport } from "./routes/overview";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as ToolsRouteImport } from "./routes/tools";
import { Route as WorkbenchRouteImport } from "./routes/workbench";
import { Route as WorkbenchMaintenanceRouteImport } from "./routes/workbench.maintenance";

const OverviewRoute = OverviewRouteImport.update({
  id: "/overview",
  path: "/overview",
  getParentRoute: () => rootRouteImport,
} as any);
const ToolsRoute = ToolsRouteImport.update({
  id: "/tools",
  path: "/tools",
  getParentRoute: () => rootRouteImport,
} as any);
const WorkbenchRoute = WorkbenchRouteImport.update({
  id: "/workbench",
  path: "/workbench",
  getParentRoute: () => rootRouteImport,
} as any);
const WorkbenchMaintenanceRoute = WorkbenchMaintenanceRouteImport.update({
  id: "/workbench/maintenance",
  path: "/workbench/maintenance",
  getParentRoute: () => rootRouteImport,
} as any);
const LibraryRoute = LibraryRouteImport.update({
  id: "/library",
  path: "/library",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const LogsRoute = LogsRouteImport.update({
  id: "/logs",
  path: "/logs",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/library": typeof LibraryRoute;
  "/logs": typeof LogsRoute;
  "/overview": typeof OverviewRoute;
  "/settings": typeof SettingsRoute;
  "/tools": typeof ToolsRoute;
  "/workbench": typeof WorkbenchRoute;
  "/workbench/maintenance": typeof WorkbenchMaintenanceRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/library": typeof LibraryRoute;
  "/logs": typeof LogsRoute;
  "/overview": typeof OverviewRoute;
  "/settings": typeof SettingsRoute;
  "/tools": typeof ToolsRoute;
  "/workbench": typeof WorkbenchRoute;
  "/workbench/maintenance": typeof WorkbenchMaintenanceRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/library": typeof LibraryRoute;
  "/logs": typeof LogsRoute;
  "/overview": typeof OverviewRoute;
  "/settings": typeof SettingsRoute;
  "/tools": typeof ToolsRoute;
  "/workbench": typeof WorkbenchRoute;
  "/workbench/maintenance": typeof WorkbenchMaintenanceRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/about"
    | "/library"
    | "/logs"
    | "/overview"
    | "/settings"
    | "/tools"
    | "/workbench"
    | "/workbench/maintenance";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/about"
    | "/library"
    | "/logs"
    | "/overview"
    | "/settings"
    | "/tools"
    | "/workbench"
    | "/workbench/maintenance";
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/library"
    | "/logs"
    | "/overview"
    | "/settings"
    | "/tools"
    | "/workbench"
    | "/workbench/maintenance";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  LibraryRoute: typeof LibraryRoute;
  LogsRoute: typeof LogsRoute;
  OverviewRoute: typeof OverviewRoute;
  SettingsRoute: typeof SettingsRoute;
  ToolsRoute: typeof ToolsRoute;
  WorkbenchRoute: typeof WorkbenchRoute;
  WorkbenchMaintenanceRoute: typeof WorkbenchMaintenanceRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/tools": {
      id: "/tools";
      path: "/tools";
      fullPath: "/tools";
      preLoaderRoute: typeof ToolsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/library": {
      id: "/library";
      path: "/library";
      fullPath: "/library";
      preLoaderRoute: typeof LibraryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/workbench": {
      id: "/workbench";
      path: "/workbench";
      fullPath: "/workbench";
      preLoaderRoute: typeof WorkbenchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/workbench/maintenance": {
      id: "/workbench/maintenance";
      path: "/workbench/maintenance";
      fullPath: "/workbench/maintenance";
      preLoaderRoute: typeof WorkbenchMaintenanceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/logs": {
      id: "/logs";
      path: "/logs";
      fullPath: "/logs";
      preLoaderRoute: typeof LogsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/overview": {
      id: "/overview";
      path: "/overview";
      fullPath: "/overview";
      preLoaderRoute: typeof OverviewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LibraryRoute: LibraryRoute,
  LogsRoute: LogsRoute,
  OverviewRoute: OverviewRoute,
  SettingsRoute: SettingsRoute,
  ToolsRoute: ToolsRoute,
  WorkbenchRoute: WorkbenchRoute,
  WorkbenchMaintenanceRoute: WorkbenchMaintenanceRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();
