import { AGGREGATION_PRIORITY_FIELDS } from "@mdcz/shared/settingsRegistry";

export interface SettingsFormExcludedField {
  key: string;
  reason: string;
}

/** Direct `name=` / section keys rendered by the settings form, excluding aggregation.fieldPriorities.*. */
export const SETTINGS_FORM_DIRECT_FIELD_KEYS = [
  "paths.mediaPath",
  "paths.metadataPath",
  "paths.actorPhotoFolder",
  "paths.softlinkPath",
  "paths.successOutputFolder",
  "paths.failedOutputFolder",
  "paths.defaultScanExcludeDirs",
  "paths.outputSummaryPath",
  "paths.sceneImagesFolder",
  "paths.configDirectory",
  "scrape.sites",
  "scrape.filenameIgnoreTokens",
  "scrape.filenameBlacklistTokens",
  "scrape.threadNumber",
  "scrape.javdbDelaySeconds",
  "scrape.restAfterCount",
  "scrape.restDuration",
  "network.proxyType",
  "network.proxy",
  "network.useProxy",
  "network.timeout",
  "network.retryCount",
  "network.javdbCookie",
  "network.javbusCookie",
  "network.fantiaCookie",
  "aggregation.maxParallelCrawlers",
  "aggregation.perCrawlerTimeoutMs",
  "aggregation.globalTimeoutMs",
  "download.downloadThumb",
  "download.downloadPoster",
  "download.tagBadges",
  "download.tagBadgeTypes",
  "download.tagBadgePosition",
  "download.tagBadgeImageOverrides",
  "download.downloadFanart",
  "download.downloadSceneImages",
  "download.downloadTrailer",
  "download.sceneImageConcurrency",
  "download.generateNfo",
  "download.nfoNaming",
  "download.nfoIgnoreFields",
  "download.keepThumb",
  "download.keepPoster",
  "download.keepFanart",
  "download.keepSceneImages",
  "download.keepTrailer",
  "download.keepNfo",
  "naming.folderTemplate",
  "naming.fileTemplate",
  "titleRepair.enabled",
  "titleRepair.rules",
  "naming.assetNamingMode",
  "naming.nfoTitleTemplate",
  "naming.actorNameMax",
  "naming.actorNameMore",
  "naming.actorFallbackToStudio",
  "naming.releaseRule",
  "naming.folderNameMax",
  "naming.fileNameMax",
  "naming.cnwordStyle",
  "naming.umrStyle",
  "naming.leakStyle",
  "naming.uncensoredStyle",
  "naming.censoredStyle",
  "naming.partStyle",
  "aggregation.behavior.preferLongerPlot",
  "aggregation.behavior.maxSceneImages",
  "aggregation.behavior.maxActors",
  "aggregation.behavior.maxGenres",
  "translate.enableTranslation",
  "translate.engine",
  "translate.llmModelName",
  "translate.llmApiKey",
  "translate.llmBaseUrl",
  "translate.llmPrompt",
  "translate.llmTemperature",
  "translate.llmTimeout",
  "translate.llmMaxRetries",
  "translate.llmMaxRequestsPerSecond",
  "translate.targetLanguage",
  "shortcuts.startOrStopScrape",
  "shortcuts.retryScrape",
  "shortcuts.deleteFile",
  "shortcuts.deleteFileAndFolder",
  "shortcuts.openFolder",
  "shortcuts.editNfo",
  "shortcuts.playVideo",
  "ui.showLogsPanel",
  "ui.useCustomTitleBar",
  "ui.hideDock",
  "ui.hideMenu",
  "ui.hideWindowButtons",
  "behavior.successFileMove",
  "behavior.failedFileMove",
  "behavior.successFileRename",
  "behavior.deleteEmptyFolder",
  "behavior.scrapeSoftlinkPath",
  "behavior.saveLog",
] as const;

export const SETTINGS_FORM_FIELD_KEYS = [
  ...SETTINGS_FORM_DIRECT_FIELD_KEYS,
  ...AGGREGATION_PRIORITY_FIELDS.map((entry) => entry.key),
] as const;

export const SETTINGS_FORM_EXCLUDED_FIELDS = [
  {
    key: "scrape.r18MetadataLanguage",
    reason: "hidden; R18 language is owned by SitePriorityEditorField, not a standalone settings row.",
  },
  {
    key: "personSync.personOverviewSources",
    reason: "tools surface; PersonServerSettingsDialog owns person overview sources.",
  },
  {
    key: "personSync.personImageSources",
    reason: "tools surface; PersonServerSettingsDialog owns person image sources.",
  },
  { key: "jellyfin.url", reason: "tools surface; JellyfinSection in PersonServerSettingsDialog." },
  { key: "jellyfin.apiKey", reason: "tools surface; JellyfinSection in PersonServerSettingsDialog." },
  { key: "jellyfin.userId", reason: "tools surface; JellyfinSection in PersonServerSettingsDialog." },
  {
    key: "jellyfin.refreshPersonAfterSync",
    reason: "tools surface; JellyfinSection in PersonServerSettingsDialog.",
  },
  {
    key: "jellyfin.lockOverviewAfterSync",
    reason: "tools surface; JellyfinSection in PersonServerSettingsDialog.",
  },
  { key: "emby.url", reason: "tools surface; EmbySection in PersonServerSettingsDialog." },
  { key: "emby.apiKey", reason: "tools surface; EmbySection in PersonServerSettingsDialog." },
  { key: "emby.userId", reason: "tools surface; EmbySection in PersonServerSettingsDialog." },
  {
    key: "emby.refreshPersonAfterSync",
    reason: "tools surface; EmbySection in PersonServerSettingsDialog.",
  },
] as const satisfies readonly SettingsFormExcludedField[];
