export {
  AGGREGATION_PRIORITY_KEYS,
  type AggregationPriorityKey,
  FIELD_KEYS,
  FIELD_REGISTRY,
  FIELD_REGISTRY_BY_KEY,
  type FieldAnchor,
  type FieldEntry,
  type FieldKey,
  type FieldVisibility,
  flattenConfig,
  getNestedValue,
  isFieldAnchor,
  isFieldManagedBySettingsSearch,
  isRecord,
  SECTION_ORDER,
  setNestedValue,
  unflattenConfig,
} from "@mdcz/shared/settingsRegistry";
